version: "3.6"

services:
    nginx:
        image: easybar/nginx:dev
        depends_on:
            - app
        environment:
            - DOCROOT=/srv
        volumes:
            - .:/srv
        ports:
            - "8090:80"
    app:
        image: easybar/php:7.2.9-dev
        volumes:
            - .:/srv
volumes:
    db-data: {}
